controller_manager:
  ros__parameters:
    update_rate: 60

    arm_cont_l:
      type: joint_trajectory_controller/JointTrajectoryController
    
    arm_cont_r:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_cont_l:
  ros__parameters:

    joints:
      - joint_1_l
      - joint_2_l
      - joint_3_l
      - joint_4_l
      - joint_5_l
      - joint_6_l

    command_interfaces:
      - position
      # - velocity
    
    state_interfaces:
      - position
      - velocity

    open_loop_controller: true
    allow_integration_in_goal_trajectory: true

arm_cont_r:
  ros__parameters:

    joints:
      - joint_1_r
      - joint_2_r
      - joint_3_r
      - joint_4_r
      - joint_5_r
      - joint_6_r

    command_interfaces:
      - position
      # - velocity
    
    state_interfaces:
      - position
      - velocity

    open_loop_controller: true
    allow_integration_in_goal_trajectory: true