controller_manager:
  ros__parameters:
    update_rate: 60

    arm_cont:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    # robotiq_activation_controller:
    #   type: robotiq_controllers/RobotiqActivationController

robotiq_gripper_controller:
  ros__parameters:
    # default: true
    action_monitor_rate: 20.0
    allow_stalling: true
    goal_tolerance: 0.01
    joint: 'robotiq_85_left_knuckle_joint'
    max_effort: 100.0
    stall_timeout: 3.0
    stall_velocity_threshold: 0.001
    
    # use_effort_interface: true
    # use_speed_interface: true

# robotiq_activation_controller:
#   ros__parameters:
#     default: true
    
arm_cont:
  ros__parameters:

    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      # - velocity
    
    state_interfaces:
      - position
      - velocity

    open_loop_controller: true
    allow_integration_in_goal_trajectory: true