# Default initial positions for dual_arm's ros2_control fake system

initial_positions:
  joint_1_l: 0
  joint_1_r: 0
  joint_2_l: 0
  joint_2_r: 0
  joint_3_l: 0
  joint_3_r: 0
  joint_4_l: 0
  joint_4_r: 0
  joint_5_l: 0
  joint_5_r: 0
  joint_6_l: 0
  joint_6_r: 0