# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_l:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  joint_1_r:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_r:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_l:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_r:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_l:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_l:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_r:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_l:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_r:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0