# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_cont
    - robotiq_gripper_controller

  arm_cont:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
  robotiq_gripper_controller:
    type: GripperCommand
    joints:
      - robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true